name: Build LLVM

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the toolchain to build'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'YoWASP/clang'
          submodules: 'true'
          path: clang

      - uses: actions/checkout@v4
        with:
          path: 'rust_wasm'
          ref: 'gh-actions'

      - name: free space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: Setup swap space
        uses: thejerrybao/setup-swap-space@v1
        with:
          swap-size-gb: 10
          remove-existing-swap-files: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          sudo apt update
          sudo apt-get install flex bison ccache

      - name: Build WASM binaries
        working-directory: "${{ github.workspace }}/clang"
        run: |
          sed -i 's/DLLVM_TARGETS_TO_BUILD=WebAssembly/DLLVM_TARGETS_TO_BUILD="X86;AArch64;ARM;LoongArch;PowerPC;RISCV;SystemZ;NVPTX;Sparc;WebAssembly"/' build.sh
          MAKEFLAGS=-j$(nproc) ./build.sh

      - name: Rename WASI prefix
        working-directory: "${{ github.workspace }}/clang"
        run: |
          ls -l
          mv wasi-prefix dist

      - name: upload bin
        working-directory: '${{ github.workspace }}/rust_wasm'
        run: |
          # backup config_rewriter
          cp -r ${{ github.workspace }}/rust_wasm/config_rewriter /tmp/config_rewriter

          # change branch
          git fetch origin llvm-tools
          git branch -a
          git switch llvm-tools
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # reset files
          rm -rf *
          mkdir -p dist/bin

          # prepare files
          cd "${{ github.workspace }}/clang"
          tar -cvzf dist/bin/llvm.wasm.tar.gz dist/bin/llvm.wasm

          # optimize wasm
          cd /tmp/config_rewriter
          cargo run --bin wasm_optimizer -- ${{ github.workspace }}/clang/dist/bin/llvm.wasm
          mv opt.wasm ${{ github.workspace }}/rust_wasm/llvm_opt.wasm
          rm ${{ github.workspace }}/clang/dist/bin/llvm.wasm
          cd ${{ github.workspace }}/rust_wasm

          # copy files
          ls -l ${{ github.workspace }}/clang
          mv ${{ github.workspace }}/clang/dist/lib/* dist/lib/
          tar -cvzf llvm_opt.wasm.tar.gz llvm_opt.wasm
          rm llvm_opt.wasm
          git add -A
          git commit -m "reset files and add new files about llvm.wasm"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          directory: "${{ github.workspace }}/rust_wasm"
          branch: llvm-tools
