name: create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version of the toolchain to build'
        required: true
        default: 'v0.1.0'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: rust_wasm

      - name: free space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: switch branch
        working-directory: "${{ github.workspace }}/rust_wasm"
        run: |
          git pull
          git branch -a
          git switch rustc_llvm_with_lld-bins-tier2-host

      - name: create release
        working-directory: "${{ github.workspace }}/rust_wasm"
        run: |
          mkdir -p "${{ github.workspace }}/x-tools"
          cd dist/lib/rustlib

          # targets
          TARGETS=(
            "aarch64-unknown-linux-gnu"
            "aarch64-unknown-linux-musl"
            "arm-unknown-linux-gnueabi"
            "arm-unknown-linux-gnueabihf"
            "armv7-unknown-linux-gnueabihf"
            "i686-unknown-linux-gnu"
            "loongarch64-unknown-linux-gnu"
            "loongarch64-unknown-linux-musl"
            "powerpc-unknown-linux-gnu"
            "powerpc64-unknown-linux-gnu"
            "powerpc64le-unknown-linux-gnu"
            "riscv64gc-unknown-linux-gnu"
            "riscv64gc-unknown-linux-musl"
            "s390x-unknown-linux-gnu"
            "sparcv9-sun-solaris"
            "wasm32-wasip1"
            "x86_64-unknown-freebsd"
            "x86_64-unknown-illumos"
            "x86_64-unknown-linux-gnu"
            "x86_64-unknown-linux-musl"
            "x86_64-unknown-netbsd"
          )
          for target in "${TARGETS[@]}"; do
            cd "${target}"
            cd lib
            tar -czf "${{ github.workspace }}/x-tools/${target}.tar.gz" *
            cd ..
            cd ..
          done

          # bin
          cd "${{ github.workspace }}/rust_wasm"
          git switch rustc_llvm_with_lld-bins
          cp rustc_opt.wasm.tar.gz "${{ github.workspace }}/x-tools/rustc_opt.wasm.tar.gz"

      - name: upload release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            x-tools/*.tar.gz
          tag: "${{ github.event.inputs.version }}-release"
          allowUpdates: true
          prerelease: true
