name: rustc_llvm_with_lld

# gh act --job build -s GITHUB_TOKEN="$(gh auth token)" --reuse

# only self-triggered
on:
  workflow_dispatch:
    inputs:

permissions:
  packages: write
  contents: write

jobs:
  build:
    # strategy:
    #   matrix:
    #     WebAssembly: [true, false]

    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
    steps:
      - name: copy source
        uses: actions/checkout@v4
        with:
          repository: 'bjorn3/rust'
          submodules: 'true'
          ref: 'compile_rustc_for_wasm17'
          path: 'rust'

      - uses: actions/checkout@v4
        with:
          path: 'rust_wasm'
          ref: 'gh-actions'

      - name: rustbuild setup
        run: |
          sudo groupadd -r rustbuild && sudo useradd -m -r -g rustbuild rustbuild
          sudo rm -rf /x-tools
          sudo mkdir /x-tools && sudo chown rustbuild:rustbuild /x-tools
          sudo chmod 777 /x-tools
          sudo mkdir -p /tmp && sudo chown rustbuild:rustbuild /tmp
          sudo chmod 777 /tmp
          sudo chmod 777 /usr/local/lib/

      - name: install-wasi-sdk
        working-directory: '${{ github.workspace }}/rust'
        run: |
          curl -OL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-24/wasi-sdk-24.0-x86_64-linux.tar.gz
          tar -xzf wasi-sdk-24.0-x86_64-linux.tar.gz

      - name: free space
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true

          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: false

      - name: install rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: update
        run: |
          sudo apt-get update
          sudo apt upgrade -y
          sudo apt install -y build-essential cmake pkg-config libclang-dev

      # https://devkitpro.org/wiki/devkitPro_pacman

      # https://github.com/devkitPro/pacman/issues/31
      # some cases people are getting banned so we need to use docker image
      # but it's troublesome to use docker image.
      # sudo docker run -it --name devkitpro-container devkitpro/toolchain-base
      # - name: install devkitPro
      #   run: |
      #     wget https://apt.devkitpro.org/install-devkitpro-pacman
      #     chmod +x ./install-devkitpro-pacman
      #     echo y | sudo ./install-devkitpro-pacman

      # https://github.com/rust-lang/rust/blob/44f233f2519ce5d633c87c38014d03d8a5f0e810/src/ci/docker/scripts/crosstool-ng-git.sh
      - name: install crosstool-ng
        env:
          CT_NG: 1.26.0
        run: |
          sudo apt install -y flex automake bison bzip2 ca-certificates cmake curl file g++ gawk gdb git gperf help2man libncurses-dev libssl-dev libtool-bin make ninja-build patch pkg-config python3 rsync sudo texinfo unzip wget xz-utils
          curl -Lf "https://github.com/crosstool-ng/crosstool-ng/archive/crosstool-ng-$CT_NG.tar.gz" | tar xzf -
          cd crosstool-ng-crosstool-ng-$CT_NG
          sed -e "s|zlib.net/'|zlib.net/fossils'|" -i packages/zlib/package.desc
          ./bootstrap
          ./configure --prefix=/usr/local
          make -j$(nproc)
          sudo make install
          cd ..
          rm -rf crosstool-ng-crosstool-ng-$CT_NG

      - name: install loongarch64-unknown-linux-gnu
        run: |
          cd /tmp
          cp ${{ github.workspace }}/rust_wasm/loongarch64-unknown-linux-gnu.defconfig crosstool.defconfig
          bash ${{ github.workspace }}/rust_wasm/crosstool-ng-build.sh
          echo "/x-tools/loongarch64-unknown-linux-gnu/bin" >> $GITHUB_PATH

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: install ndk
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
          link-to-sdk: true
          local-cache: false

      - name: install ndk path
        run: |
          ls -l ${{ steps.setup-ndk.outputs.ndk-path }}
          mkdir -p ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/aarch64-linux-android-clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/i686-linux-android-clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/arm-linux-androideabi-clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/riscv64-linux-android35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/riscv64-linux-android-clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/x86_64-linux-android-clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/clang'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android35-clang' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/aarch64-linux-android-clang++'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android35-clang++' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/i686-linux-android-clang++'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi35-clang++' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/arm-linux-androideabi-clang++'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/riscv64-linux-android35-clang++' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/riscv64-linux-android-clang++'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang++' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/x86_64-linux-android-clang++'
          sudo ln -sf '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++' '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/clang++'

          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/aarch64-linux-android-clang'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/i686-linux-android-clang'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/arm-linux-androideabi-clang'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/riscv64-linux-android-clang'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/x86_64-linux-android-clang'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/aarch64-linux-android-clang++'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/i686-linux-android-clang++'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/arm-linux-androideabi-clang++'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/riscv64-linux-android-clang++'
          sudo chmod +x '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins/x86_64-linux-android-clang++'

          echo '${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bins' >> $GITHUB_PATH

          echo 'ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}' >> $GITHUB_ENV

      - name: check clang
        run: |
          clang --version
          x86_64-linux-android-clang --version

      # https://pkgsrc.smartos.org/install-on-linux/
      - name: install pkgsrc about netbsd
        run: |
          sudo apt install -y cvs libncurses-dev gcc g++ zlib1g-dev zlib1g libssl-dev libudev-dev gawk unzip curl
          curl -OL https://cdn.netbsd.org/pub/pkgsrc/stable/pkgsrc.tar.xz
          tar -xJf pkgsrc.tar.xz
          rm -f pkgsrc.tar.xz
          rm -rf pkgsrc/bootstrap/work
          rm -rf /usr/pkg
          sudo rm -rf /root/pkg
          cd pkgsrc/bootstrap
          ./bootstrap --unprivileged

          echo "/usr/pkg/sbin" >> $GITHUB_PATH
          echo "/usr/pkg/bin" >> $GITHUB_PATH

      - name: install dependencies
        run: |
          sudo apt install -y gcc-multilib              g++-multilib
          sudo apt install -y gcc-riscv64-linux-gnu     g++-riscv64-linux-gnu     libc6-dev-riscv64-cross
          sudo apt install -y gcc-riscv64-unknown-elf
          sudo apt install -y gcc-powerpc64-linux-gnu   g++-powerpc64-linux-gnu   libc6-dev-ppc64-powerpc-cross
          sudo apt install -y gcc-powerpc-linux-gnu     g++-powerpc-linux-gnu     libc6-dev-ppc64-powerpc-cross
          sudo apt install -y gcc-powerpc64le-linux-gnu g++-powerpc64le-linux-gnu
          sudo apt install -y gcc-aarch64-linux-gnu     g++-aarch64-linux-gnu
          sudo apt install -y gcc-arm-linux-gnueabihf   g++-arm-linux-gnueabihf
          sudo apt install -y gcc-arm-linux-gnueabi     g++-arm-linux-gnueabi
          sudo apt install -y gcc-s390x-linux-gnu       g++-s390x-linux-gnu       linux-libc-dev-s390x-cross
          sudo apt install -y gcc-sparc64-linux-gnu     g++-sparc64-linux-gnu
          sudo apt install -y gcc-i686-linux-gnu        g++-i686-linux-gnu
          sudo apt install -y gcc-arm-none-eabi

      - name: install musl base
        run: |
          sudo apt install -y musl-dev musl-tools musl
          rm -rf ~/build/

      - name: install musl dependencies armv7
        env:
          CC: arm-linux-gnueabi-gcc
          CXX: arm-linux-gnueabi-g++
          CFLAGS: '-march=armv7-a'
          CXXFLAGS: '-march=armv7-a'
        run: |
          mkdir ~/build
          cd ~/build
          bash '${{ github.workspace }}/rust_wasm/musl.sh' armv7
          cd /
          rm -rf ~/build/

      - name: install musl dependencies riscv64gc
        env:
          CC: riscv64-linux-gnu-gcc
          CXX: riscv64-linux-gnu-g++
        run: |
          mkdir ~/build
          cd ~/build
          bash '${{ github.workspace }}/rust_wasm/musl.sh' riscv64gc
          cd /
          rm -rf ~/build/

      - name: install musl dependencies i686 i586
        env:
          CC: i686-linux-gnu-gcc
          CXX: i686-linux-gnu-g++
          CFLAGS: '-m32 -Wa,-mrelax-relocations=no'
          CXXFLAGS: '-m32 -Wa,-mrelax-relocations=no'
        run: |
          mkdir ~/build
          cd ~/build
          bash '${{ github.workspace }}/rust_wasm/musl.sh' i686 --target=i686
          cd /
          rm -rf ~/build/
          mkdir ~/build
          cd ~/build
          bash '${{ github.workspace }}/rust_wasm/musl.sh' i586 --target=i586
          cd /
          rm -rf ~/build/

      - name: install musl dependencies aarch64
        env:
          CFLAGS: "-Wa,--compress-debug-sections=none -Wl,--compress-debug-sections=none"
          CXXFLAGS: "-Wa,--compress-debug-sections=none -Wl,--compress-debug-sections=none"
        run: |
          mkdir ~/build
          cd ~/build
          bash '${{ github.workspace }}/rust_wasm/musl-toolchain.sh' aarch64
          cd /
          rm -rf ~/build/

      - name: rewrite
        run: |
          cd rust_wasm/config_rewriter
          cargo run -- ../../rust/config.llvm.toml all linux
          cargo clean
          echo "rewrite done"

      - name: build
        working-directory: '${{ github.workspace }}/rust'
        env:
          WASI_SDK_PATH: ${{ github.workspace }}/rust/wasi-sdk-24.0-x86_64-linux
        run: |
          ./x.py install --config config.llvm.toml

      - name: create tarball
        working-directory: '${{ github.workspace }}/rust'
        run: |
          tar -cvzf dist/bin/rustc.wasm.tar.gz dist/bin/rustc.wasm
          rm dist/bin/rustc.wasm

      - name: Configure git to trust the workspace despite the different owner
        run:
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: upload bin
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: rust/dist/bin
          branch: rustc_llvm_with_lld
          target-folder: rustc_llvm_with_lld/dist/bin
          clean: false
          commit-message: "update bin"

      # - name: upload wasm32-unknown-unknown
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: rust/dist/lib/rustlib/wasm32-unknown-unknown
      #     branch: rustc_llvm_with_lld
      #     target-folder: rustc_llvm_with_lld/dist/lib/rustlib/wasm32-unknown-unknown
      #     clean: false
      #     commit-message: "update wasm32-unknown-unknown"

      - name: upload wasm32-wasip1
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: rust/dist/lib/rustlib/wasm32-wasip1
          branch: rustc_llvm_with_lld
          target-folder: rustc_llvm_with_lld/dist/lib/rustlib/wasm32-wasip1
          clean: false
          commit-message: "update wasm32-wasip1"

      # - name: upload wasm32-wasip1-threads
      #   uses: JamesIves/github-pages-deploy-action@v4
      #   with:
      #     folder: rust/dist/lib/rustlib/wasm32-wasip1-threads
      #     branch: rustc_llvm_with_lld
      #     target-folder: rustc_llvm_with_lld/dist/lib/rustlib/wasm32-wasip1-threads
      #     clean: false
      #     commit-message: "update wasm32-wasip1-threads"

      - name: upload x86_64-unknown-linux-gnu
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: rust/dist/lib/rustlib/x86_64-unknown-linux-gnu
          branch: rustc_llvm_with_lld
          target-folder: rustc_llvm_with_lld/dist/lib/rustlib/x86_64-unknown-linux-gnu
          clean: false
          commit-message: "update x86_64-unknown-linux-gnu"
